config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :deals
  get 'sell_product', to: 'deals#sell_product'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
	belongs_to :user
	has_many :transaction_histories
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	validates :price, :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validates :publish_date, :discount, presence: true
	has_one_attached :image

	validate :validate_deal_attributes
	enum state: { archive: 1, active: 2}

	def validate_deal_attributes
		is_published = Deal.where(publish_date: publish_date).size
		if publish_date.past? or publish_date.today?
			errors.add(:base, "publish date will be of future only")
		elsif is_published > 0
			errors.add(:base, "Only one deal can be published on a day, please publish on other days!")
		end
	end

	def is_already_purchased?(user)
		!transaction_histories.where(user: user)
	end
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
	belongs_to :deal
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :deals, dependent: :destroy
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, uniqueness: {case_sensitive: false}, 
                            presence: true, length: {minimum: 3, maximum: 25}
    validates :email, uniqueness: {case_sensitive: false}, 
                        presence: true, length: {maximum: 105},
                        format: { with: VALID_EMAIL_REGEX }
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def current_user
			@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
			!!current_user
	end

	def require_user
		if !logged_in?
				flash[:alert] = "You must be logged in to perform this action."
				redirect_to login_path
		end
	end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

    # after_action, around_action : HW
	before_action :set_deal, only: [:show, :edit, :update, :destroy, :sell_product]
	before_action :require_user
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
	end
	
	def index
		@deals = Deal.where(state: 'active')
	end
	
	def edit
	end

	def new
			@deal = Deal.new
	end

	def create
		@deal = Deal.new(deal_params)
		@deal.user = current_user
		if @deal.save
				flash[:notice] = "Deal was created successfully."
				redirect_to deal_path(@deal)
		else 
				render 'new'
		end
	end

	def update
		if @deal.update(deal_params)
				flash[:notice] = "Deal was updated successfully."
				redirect_to @deal
		else
				render 'edit'
		end
	end

	def destroy
		@deal.destroy
		redirect_to deals_path
	end

	def sell_product
		Deal.transaction do
			if @deal.is_already_purchased?(current_user)
				@deal.update!(quantity: @deal.quantity - 1)
				flash[:notice] = "Successfully purchased the product"
			else
				flash[:error] = "Deal can be used single time by a user"
			end
		end
		redirect_back(fallback_location: root_path)
	end

	private

	def set_deal
		@deal = Deal.find(params[:id])
	end

	def deal_params
		params.require(:deal).permit(Deal.columns.map(&:name))
	end

	def require_same_user
		if current_user != @deal.user && !current_user.admin?
			flash[:alert] = "You can only edit or delete your own deal."
			redirect_to @deal
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to deals_path if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
				session[:user_id] = user.id
				flash[:notice] = "Logged in successfully"
				redirect_to user
		else
				flash.now[:alert] = "There was something wrong with your login credentials."
				render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @deals = @user.deals.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information is successfully updated."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to MVP Sale Site, you have successfully signed up."
            redirect_to deals_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated deals successfully deleted"
        redirect_to deals_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own account."
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, option = {size: 80})
		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		size = option[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
	end

	def get_discount_price(price, discount)
		(price * (100 - discount) / 100)
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/deals/_deal.html.erb
<div class="container">
	<% @deals.each do |deal| %>
		<div class="row justify-content-center">
			<div class="col-8 mt-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header fst-italic">
						<% if deal.user %>
							by <%= link_to deal.user.username, user_path(deal.user) %>
						<% end %>
					</div>
					<%= render partial: 'deals/details', locals: { deal: deal } %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/deals/_details.html.erb
<div class="card-body">
	<h5 class="card-title">
			<%= link_to deal.title, deal_path(deal), class: "text-success" %>
	</h5>
	<p class="card-text">
			<%= truncate(deal.description, length: 100) %>
	</p>
	<p class="card-text"><em><b>Price: </b></em>₹ <%= deal.price %></p>
	<p class="card-text"><em><b>Discount: </b></em>₹ <%= get_discount_price(deal.price.to_f, deal.discount.to_f) %></p>
	<p class="card-text"><em><b>Quantity: </b></em><%= deal.quantity %></p>
	<p class="card-text"><em><b>Publish date: </b></em><%= deal.publish_date.strftime("%a, #{deal.publish_date.day.ordinalize} %b %Y") %></p>
	<p class="card-text"><em><b><%= image_tag(deal.image, style: "width: 100px") %></p>
	<%= link_to "Buy", sell_product_path(id: deal.id), class: "btn btn-outline-success", :data => {:confirm => 'Are you sure?'} if deal.quantity > 0 and deal.is_already_purchased?(current_user) %>
	<%= link_to "View", deal_path(deal), class: "btn btn-outline-success" %>
	<% if logged_in? && (deal.user == current_user || current_user.admin?) %>
			<%= link_to "Edit" , edit_deal_path(deal), class: "btn btn-outline-info" %>
			<%= link_to "Delete" , deal_path(deal), method: :delete,
									class: "btn btn-outline-danger" , data: {confirm: "Are you sure ?" }%>
	<% end %>
</div>
<div class="card-footer text-muted">
		Published before <%= time_ago_in_words(deal.created_at) %> ago,
		Edited <%= time_ago_in_words(deal.updated_at) %> ago
</div>

app/views/deals/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @deal %> 
			<%= form_with(model: @deal, class: "shadow p-3 mb-3 custom-bg rounded", local: true) do |f|%>
					<div class="form-group row mt-2">
						<%= f.label :title, class: "col-2 col-form-label" %>
						<div class="col-10">
								<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of deal", required: true %>
						</div>
					</div>

					<div class="form-group row mt-2">
						<%= f.label :description, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of deal", required: true %>
						</div>
					</div>
					<div class="form-group row mt-2">
						<%= f.label :price, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.number_field :price, min: 1, class: "form-control shadow rounded", placeholder: "Price of product", onchange: "this.value = validateUserInputPrice(this)", required: true %>
						</div>
					</div>
					<div class="form-group row mt-2">
						<%= f.label :discount, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.number_field :discount, min: 0, max: 100, class: "form-control shadow rounded", placeholder: "Enter Discount in percentage", onchange: "this.value = validateUserInputAmount(this)", required: true %>
						</div>
					</div>


					<div class="form-group row mt-2">
						<%= f.label :quantity, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.number_field :quantity, min: 0, class: "form-control shadow rounded", placeholder: "Quantity of deal", onchange: "this.value = validateUserInputAmount(this)", required: true %>
						</div>
					</div>


					<div class="form-group row mt-2">
						<%= f.label :publish_date, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.date_field :publish_date, min: Date.today + 1, class: "form-control shadow rounded", placeholder: "Publish date of deal", required: true %>
						</div>
					</div>


					<div class="form-group row mt-2">
						<%= f.label :image, class: "col-2 col-form-label" %>
						<div class="col-10">
							<%= f.file_field :image, class: "form-control shadow rounded", placeholder: "Image of product", required: true %>
						</div>
					</div>

					<div class="text-center mt-3">
							<%= f.submit class: "btn btn-outline-light btn-lg" %>
					</div>
			<% end %>
		</div>
				
		<div class="text-center mt-3 mb-3">
			<%= link_to "[ Cancel and return to deals listing ]", deals_path, class: "text-info cancel-btn" %>
		</div>
  </div>
</div>

<script>
	function validateUserInputAmount(event) {
		return (Math.abs(event.value).toFixed(2) > 100 ? 100 : Math.abs(event.value).toFixed(2));
	}
	function validateUserInputPrice(event) {
		return (Math.abs(event.value).toFixed(2) < 0 ? 0 : Math.abs(event.value).toFixed(2));
	}
</script>

app/views/deals/edit.html.erb
<h1 class="text-center mt-4">Edit deal</h1>
<%= render 'form' %>

app/views/deals/index.html.erb
<h1 class="text-center mt-4">Today's Deal</h1>

<% if @deals.present? %>
	<%= render 'deal' %>
<% else %>
	<p class="center-text">There is no active deal for today!</p>
<% end %>

app/views/deals/new.html.erb
<h1 class="text-center mt-4">Create a new deal</h1>
<%= render 'form' %>

app/views/deals/show.html.erb
<h2 class="text-center mt-4"><%= @deal.title %></h1>

<div class="row justify-content-center">
	<div class="col-8 mt-4">
		<div class="card text-center shadow mb-5 bg-white rounded">
			<div class="card-header fst-italic">
			by <%= @deal.user.username if @deal.user %>
			<%= link_to gravatar_for(@deal.user), user_path(@deal.user) %>
			</div>
			<div class="card-body">
				<% if logged_in? && (@deal.user == current_user || current_user.admin?) %>
					<%= link_to "Edit" , edit_deal_path(@deal), class: "btn btn-outline-info" %>
					<%= link_to "Delete" , deal_path(@deal), method: :delete,
											class: "btn btn-outline-danger" , data: {confirm: "Are you sure ?" }%>
				<% end %>
			</div>
			<%= render partial: 'details', locals: { deal: @deal } %>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Akash Vishwakarma", "#", class: "text-white"%></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Sale Site", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Deals
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user.admin? %>
                <%= link_to "Create new deal", new_deal_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "View deals", deals_path, class: "dropdown-item" %>
            </ul>
          </li>
        <% end %>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure ?"} %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>This is a MVP Sale Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">This is MVP Sale Site</h1>
      <hr class="my-4">
      <p class="lead">Login to see current active deals</p>
      <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg sign-up" %>
      <p class="lead">You can join as membership user and get amazing sale every day at 10 AM</p>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h2>
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li>
                        <%= msg %>
                    </li>
                    <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>

app/views/users/_form.html.erb
<div class="container">
<div class="row justify-content-center">
<div class="col-10">
<%= render 'shared/errors', obj: @user %> 
            <%= form_with(model: @user, class: "shadow p-3 mb-3 custom-bg rounded", local: true) do |f|%>
                <div class="form-group row mt-2">
                    <%= f.label :username, class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
                    </div>
                </div>

                <div class="form-group row mt-2">
                    <%= f.label :email, class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
                    </div>
                </div>

                <div class="form-group row mt-2">
                    <%= f.label :password, class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Chosse a password" %>
                    </div>
                </div>

                <div class="text-center mt-3">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
                </div>
            <% end %>
        </div>
        
        <div class="text-center mt-3 mb-3">
          <%= link_to "[ Cancel and return to deals listing ]", deals_path, class: "text-info cancel-btn" %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Sign up for Sale Site</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">MVP Sale Site</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header fst-italic">
                        <%= link_to user.username, user%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to gravatar_for(user, size: 150), user %>
                        </h5>
                        <p class="card-text">
                            <%= pluralize(user.deals.count, "deal") %>
                        </p>
                        <%= link_to "View Profile" , user, class: "btn btn-outline-success" %>
                        <% if logged_in? %>
                            <% if user == current_user %>
                                <%= link_to "Edit Profile" , edit_user_path(user), class: "btn btn-outline-info" %>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete the user account and all associated deals ?"} %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        Joined <%= time_ago_in_words(user.created_at) %> ago
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Sale Site</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4">
    <%= @user.username %>'s Profile
</h1>

<%= gravatar_for @user, size: 200%>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile" , edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Deals</h3>
<%= render 'deals/deal' %>